name: flutter_cache_pro
description: Professional caching solution with LRU, TTL, priority levels, memory and disk storage for Flutter applications.
version: 1.0.0
homepage: https://github.com/flixelo/flutter_cache_pro
repository: https://github.com/flixelo/flutter_cache_pro
issue_tracker: https://github.com/flixelo/flutter_cache_pro/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  path: ^1.8.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
